---
- hosts: all
  become: true
  vars:
    pb_create_containers: 1
    pb_default_container_name: docker
    pb_default_container_image: alpine:latest
   
  tasks:
    
    - name: Install prerequisites
      apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        update_cache: yes
      
    - name: Add Docker GPG apt Key in playbook
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository in playbook
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce in playbook
      apt: update_cache=yes name=docker-ce state=latest


    # Pull default docker image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ pb_default_container_image }}"
        source: pull

    # Create the specified number of containers in pb_create_containers
    - name: Create default containers
      docker_container:
        name: "{{ pb_default_container_name }}{{ item }}"
        image: "{{ pb_default_container_image }}"
        state: started
      with_sequence: count={{ pb_create_containers }}
    
    # Install nginx with web server
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Upload default index.html for host
      copy: src=web_files/index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
    - name: start nginx
      service: name=nginx state=started
          state: started
