---
- hosts: all
  become: true
  vars:
    pb_create_containers: 1
    pb_default_container_name: docker
    pb_default_container_image: ubuntu
    pb_default_container_command: sleep 1d

  tasks:
    
    - name: Install prerequisites
      apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        update_cache: yes
      
    - name: Add Docker GPG apt Key in playbook
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository in playbook
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce in playbook
      apt: update_cache=yes name=docker-ce state=latest


    # Pull default docker image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ pb_default_container_image }}"
        source: pull

    # Create the specified number of containers in pb_create_containers
    - name: Create default containers
      docker_container:
        name: "{{ pb_default_container_name }}{{ item }}"
        image: "{{ pb_default_container_image }}"
        command: "{{ pb_default_container_command }}"
        state: present
      with_sequence: count={{ pb_create_containers }}
      
